### ISSUE TITLE
Error in russian translation 

### ISSUE THREAD

**Issue by tsirulnikovm** [arl1nd/Kalium-Translations#1]
170 #: inc/functions/template/blog-template-functions.php:1093
171 msgid "Older Post"
172 msgstr "Cтарая Почта"

174 #: inc/functions/template/blog-template-functions.php:1100
175 msgid "Newer Post"
176 msgstr "Более новая Почта"

Instead "Cтарая Почта"  should be "Предыдущая публикация"
Instead "Более новая Почта"  should be "Следующая публикация"

**Comment by yllip** [comment]
Thanks for your report, we will fix this problem in the next Kalium theme update 👍

**Comment by arl1nd** [comment]
The fix is applied now.
